from typing import Sequence
from sqlalchemy.orm import Session
from app.crud.base import CRUDBase
from app.models.wgserver import WGServer
from app.schemas.wgserver import WGServerCreate,WGServerUpdate
import subprocess
from app.core.Settings import get_settings
import logging
# from .wg_server import server
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
settings = get_settings()

class CRUDWGServer(CRUDBase[WGServer,WGServerCreate,WGServerUpdate]):
    def get_server_config(self, session: Session) -> WGServer:
        server = session.query(self.model).first()
        print('-->here',session.query(WGServer).all())
        print(server)
        return server

        # new_config = self.new_server_credentials()
        # new_orm_config = WGServer(
        #     # new_config.model_dump()
        #     privateKey=new_config.privateKey,
        #     publicKey=new_config.publicKey,
        #     address=new_config.address,
        # )
        # self.save(session=session,obj=new_orm_config)
        # return new_orm_config
    def save_wgserver_dot_conf(self,orm_server:WGServer):
        result = f"""
# Note: Do not edit this file directly.
# Your changes will be overwritten!

# Server
[Interface]
PrivateKey = {orm_server.privateKey}
Address = {orm_server.address}/24
ListenPort = {settings.WG_PORT}
PreUp = {settings.WG_PRE_UP}
PostUp = {settings.WG_POST_UP}
PreDown = {settings.WG_PRE_DOWN}
PostDown = {settings.WG_POST_DOWN}"""
        # clients = self.config['clients']
        # all_db_clients=db.query(Client).all()
        for client in orm_server.clients:
            if not client.enabled:
                continue
            pre_shared_key=client.preSharedKey
            if pre_shared_key:
                pre_shared_key_str = f'PresharedKey = {pre_shared_key}'
            else:
                pre_shared_key_str = ''
            result += f"""
# Client: {client.name} ({client.id})
[Peer]
PublicKey = {client.publicKey}
{pre_shared_key_str}
AllowedIPs = {client.address}/32"""
        logger.debug('Config saving...')
        with open(f"{settings.WG_CONFIG_PATH}wg0.conf","w") as f :
            f.write(result)
        # with open(f"{WG_CONFIG_PATH}wg0.json", "w") as f:
        #     json_object = json.dumps(self.config,indent=4)
            # f.write(json_object)
        logger.debug('Config saved.')
    def new_server_credentials(self):
        command = ["wg","pubkey"]
        proc = subprocess.Popen(
            command,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            # executable='/bin/bash'
        )
        privateKey = subprocess.run(['wg', 'genkey'],stdout=subprocess.PIPE).stdout.decode().strip()
        privateToBytes = bytes(privateKey,'utf-8')
        (stdoutData, stderrData) = proc.communicate(privateToBytes)
        publicKey=stdoutData.decode().strip()
        address = settings.WG_DEFAULT_ADDRESS.replace('x', '1')
        return WGServerCreate(
            address=address,
            privateKey=privateKey,
            publicKey=publicKey
        )
    def sync_wg_quicks_strip(self):
        logger.debug('Config syncing...')
        (exit_code,output)=subprocess.getstatusoutput('wg syncconf wg0 <(wg-quick strip wg0)')
        logger.debug('Config synced.')

    def save_and_sync_wg_config(self,wgserver:WGServer):
        # client_list =wgserver.clients
        self.save_wgserver_dot_conf(orm_server=wgserver)
        self.sync_wg_quicks_strip()
        
crud_wgserver=CRUDWGServer(WGServer)