"""alter latest_handshake_at to last_handshake_at

Revision ID: 07d6c15b1d68
Revises: 5243fc566f2c
Create Date: 2024-05-17 02:33:40.216933+03:30

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07d6c15b1d68'
down_revision: Union[str, None] = '5243fc566f2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peer', sa.Column('last_handshake_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.drop_index('ix_peer_latest_handshake_at', table_name='peer')
    op.create_index(op.f('ix_peer_last_handshake_at'), 'peer', ['last_handshake_at'], unique=False)
    op.drop_column('peer', 'latest_handshake_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peer', sa.Column('latest_handshake_at', sa.TIMESTAMP(), nullable=True))
    op.drop_index(op.f('ix_peer_last_handshake_at'), table_name='peer')
    op.create_index('ix_peer_latest_handshake_at', 'peer', ['latest_handshake_at'], unique=False)
    op.drop_column('peer', 'last_handshake_at')
    # ### end Alembic commands ###
