"""Added client columns

Revision ID: 4ce4773bd545
Revises: 
Create Date: 2024-05-04 03:00:13.039340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce4773bd545'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=True)
    op.create_index(op.f('ix_user_updated_at'), 'user', ['updated_at'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('wgserver',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('privateKey', sa.String(length=255), nullable=False),
    sa.Column('publicKey', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wgserver_created_at'), 'wgserver', ['created_at'], unique=False)
    op.create_index(op.f('ix_wgserver_id'), 'wgserver', ['id'], unique=True)
    op.create_index(op.f('ix_wgserver_updated_at'), 'wgserver', ['updated_at'], unique=False)
    op.create_table('client',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('publicKey', sa.String(length=256), nullable=False),
    sa.Column('privateKey', sa.String(length=256), nullable=False),
    sa.Column('preSharedKey', sa.String(length=256), nullable=False),
    sa.Column('latestHandshakeAt', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('persistentKeepalive', sa.String(length=20), nullable=True),
    sa.Column('transferRx', sa.Integer(), nullable=True),
    sa.Column('transferTx', sa.Integer(), nullable=True),
    sa.Column('allowedIPs', sa.String(length=255), nullable=True),
    sa.Column('wgserver_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['wgserver_id'], ['wgserver.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_created_at'), 'client', ['created_at'], unique=False)
    op.create_index(op.f('ix_client_id'), 'client', ['id'], unique=True)
    op.create_index(op.f('ix_client_latestHandshakeAt'), 'client', ['latestHandshakeAt'], unique=False)
    op.create_index(op.f('ix_client_name'), 'client', ['name'], unique=False)
    op.create_index(op.f('ix_client_updated_at'), 'client', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_updated_at'), table_name='client')
    op.drop_index(op.f('ix_client_name'), table_name='client')
    op.drop_index(op.f('ix_client_latestHandshakeAt'), table_name='client')
    op.drop_index(op.f('ix_client_id'), table_name='client')
    op.drop_index(op.f('ix_client_created_at'), table_name='client')
    op.drop_table('client')
    op.drop_index(op.f('ix_wgserver_updated_at'), table_name='wgserver')
    op.drop_index(op.f('ix_wgserver_id'), table_name='wgserver')
    op.drop_index(op.f('ix_wgserver_created_at'), table_name='wgserver')
    op.drop_table('wgserver')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_updated_at'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
