"""Added server colomns

Revision ID: 6452a81990a1
Revises: 940e1dc69d68
Create Date: 2024-05-15 19:14:02.059790+03:30

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6452a81990a1'
down_revision: Union[str, None] = '940e1dc69d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'allowedIPs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('allowedIPs', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
