"""adding peer model

Revision ID: b8acf935fba7
Revises: 739a31ac9beb
Create Date: 2024-05-23 03:48:32.051987+03:30

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8acf935fba7'
down_revision: Union[str, None] = '739a31ac9beb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('interface_id', sa.Integer(), nullable=False),
    sa.Column('persistent_keepalive', sa.Integer(), nullable=True),
    sa.Column('allowed_ips', sa.String(length=255), nullable=True),
    sa.Column('preshared_key', sa.String(length=256), nullable=True),
    sa.Column('private_key', sa.String(length=256), nullable=False),
    sa.Column('public_key', sa.String(length=256), nullable=False),
    sa.Column('if_public_key', sa.String(length=256), server_default='', nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('transfer_rx', sa.Integer(), nullable=False),
    sa.Column('transfer_tx', sa.Integer(), nullable=False),
    sa.Column('last_handshake_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('endpoint_addr', sa.String(length=256), nullable=True),
    sa.Column('friendly_name', sa.String(length=255), nullable=True),
    sa.Column('friendly_json', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['interface_id'], ['wginterface.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peer_created_at'), 'peer', ['created_at'], unique=False)
    op.create_index(op.f('ix_peer_id'), 'peer', ['id'], unique=True)
    op.create_index(op.f('ix_peer_last_handshake_at'), 'peer', ['last_handshake_at'], unique=False)
    op.create_index(op.f('ix_peer_name'), 'peer', ['name'], unique=False)
    op.create_index(op.f('ix_peer_updated_at'), 'peer', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_peer_updated_at'), table_name='peer')
    op.drop_index(op.f('ix_peer_name'), table_name='peer')
    op.drop_index(op.f('ix_peer_last_handshake_at'), table_name='peer')
    op.drop_index(op.f('ix_peer_id'), table_name='peer')
    op.drop_index(op.f('ix_peer_created_at'), table_name='peer')
    op.drop_table('peer')
    # ### end Alembic commands ###
