"""add endpoint_addr to Peer model

Revision ID: c03735fc8b41
Revises: b530cfd2f420
Create Date: 2024-05-20 04:20:11.781425+03:30

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c03735fc8b41'
down_revision: Union[str, None] = 'b530cfd2f420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peer', sa.Column('endpoint_addr', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peer', 'endpoint_addr')
    # ### end Alembic commands ###
