"""Added client columns

Revision ID: eb3334a19feb
Revises: ca485ccb4e29
Create Date: 2024-05-04 01:26:13.834424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb3334a19feb'
down_revision: Union[str, None] = 'ca485ccb4e29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('persistentKeepalive', sa.String(length=20), nullable=True))
    op.add_column('client', sa.Column('transferRx', sa.Integer(), nullable=True))
    op.add_column('client', sa.Column('transferTx', sa.Integer(), nullable=True))
    op.add_column('client', sa.Column('allowedIPs', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_client_latestHandshakeAt'), 'client', ['latestHandshakeAt'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_latestHandshakeAt'), table_name='client')
    op.drop_column('client', 'allowedIPs')
    op.drop_column('client', 'transferTx')
    op.drop_column('client', 'transferRx')
    op.drop_column('client', 'persistentKeepalive')
    # ### end Alembic commands ###
